---

- name: check for nvidia-smi
  stat:
    path: /usr/bin/nvidia-smi
  register: nvidia_smi_path
  ignore_errors: yes


- block:
  - name: capture nvidia_smi
    command: nvidia-smi
    register: nvidia_smi_info

  - name: set the collected gpu info as facts
    set_fact:
      stockpile_gpuinfo:
        nvidia-smi: "{{ nvidia_smi_info.stdout }}"
  when: nvidia_smi_path.stat.exists

- debug:
    msg:
      - "Path exists: {{nvidia_smi_path.stat.exists}}"
